var ActionTypes = {

    ADD_ROUTE: 'ADD_ROUTE',
    ADD_ROUTE_REQUESTED: 'ADD_ROUTE_REQUESTED',
    REMOVE_ROUTE: 'REMOVE_ROUTE',
    REMOVE_ROUTE_REQUESTED: 'REMOVE_ROUTE_REQUESTED',
    CHANGE_ROUTE_NAME: 'CHANGE_ROUTE_NAME',
    CHANGE_ACTIVE_ROUTE: 'CHANGE_ACTIVE_ROUTE',
    ADD_WAY_POINT_TO_ROUTE: 'ADD_WAY_POINT_TO_ROUTE',
    REMOVE_WAY_POINT_FROM_ROUTE: 'REMOVE_WAY_POINT_FROM_ROUTE',

    ADD_WAY_POINT: 'ADD_WAY_POINT',
    ADD_WAY_POINT_REQUESTED: 'ADD_WAY_POINT_REQUESTED',
    ADD_WAY_POINT_SUCCEEDED: 'ADD_WAY_POINT_SUCCEEDED',
    REMOVE_WAY_POINT: 'REMOVE_WAY_POINT',
    REMOVE_WAY_POINT_REQUESTED: 'REMOVE_WAY_POINT_REQUESTED',
    REMOVE_WAY_POINT_SUCCEEDED: 'REMOVE_WAY_POINT_SUCCEEDED',
    CHANGE_WAY_POINT_NAME: 'CHANGE_WAY_POINT_NAME'
};

module.exports = ActionTypes;