var ActionTypes = {

    ADD_ROUTE: 'ADD_ROUTE',
    REMOVE_ROUTE: 'REMOVE_ROUTE',
    UPDATE_ROUTE_NAME: 'EDIT_ROUTE_NAME',
    CHANGE_ACTIVE_ROUTE: 'CHANGE_ACTIVE_ROUTE',
    ADD_WAY_POINT_TO_ROUTE: 'ADD_WAY_POINT_TO_ROUTE',

    ADD_WAY_POINT_REQUESTED: 'ADD_WAY_POINT_REQUESTED',
    ADD_WAY_POINT_SUCCEEDED: 'ADD_WAY_POINT_SUCCEEDED',
    ADD_WAY_POINT: 'ADD_WAY_POINT',
    REMOVE_WAY_POINT: 'REMOVE_WAY_POINT',
    UPDATE_WAY_POINT: 'UPDATE_WAY_POINT'
};

module.exports = ActionTypes;